version: '3'

services:
  database:
    container_name: container_db
    image: postgres:alpine
    environment:
      - POSTGRES_DB=postgres_db
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pass
    ports:
      - '5432'
  web:
    container_name: container_web
    restart: always
    build: .
    command: >
            bash -c "python3 manage.py migrate
            && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - database
    links:
      - database:database
